### ISSUE TITLE
Please chose a license 

### ISSUE THREAD

**Issue by SchneiderSIT** [karlisup/spotlight#3]
Hello from Germany, 

nice work here! I'd like to include this in an open source module for a content management system that is well known here. 
But I see no license here. Would be great if you'd chose a license for spotlight. 

Thanks, 
Kim

**Comment by karlisup** [comment]
Hi @SchneiderSIT,
Although haven't touched the project for 2 years I am glad that you have a purpose for it. I updated `npm` dependencies, added MIT license, and would be glad that it serves someone. Would love to see it in action if you don't mind sharing your project when it's implemented.

Best Regards,
Karlis
